### ISSUE TITLE
Publish 2.0.1 to Ruby gems

### ISSUE THREAD

**Issue by cabello** [phaxio/phaxio-ruby#21]
👋  We are pointing directly at Github because we want support to sending multiple files https://github.com/phaxio/phaxio-ruby/commit/b71abcd750dd946b22a9bf30f6b46dd743d0466a the following commit is a version bump https://github.com/phaxio/phaxio-ruby/commit/ea61db47312874b056e542b72e374abc35d846e6 but that version has not been published to Ruby gems, do you mind doing that please?

**Comment by jnankin** [comment]
This has been pushed
