### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by akaspick** [phaxio/phaxio-ruby#37]
The latest published gem is 2.0.1 from 2018.  Is this the recommended version to use still or should we be using 2.1.pre straight from the github repo?

**Comment by lucaong** [comment]
Hi @jtnegrotto ,
One compelling reason for releasing `2.1.0` is that `2.0.1` is too strict in its requirement towards Faraday (see https://github.com/phaxio/phaxio-ruby/pull/31 for the detailed discussion). This means that any app that uses an up-to-date version of Faraday will have problems with `2.0.1` (or has to resort to keep using Faraday `0.10`, but that is not possible when using other popular gems that require Faraday `~> 1.0`).

Is there a release plan for `2.1.0`? My company is among those who would benefit from `2.1.0` being published on Rubygems, as we are using our own fork until this gets resolved.

Thank you!

**Comment by lucaong** [comment]
Please note that meanwhile Faraday reached version `v2.2.0`, so it probably makes sense to check if the dependency can be relaxed further to include also that.

**Comment by billsimon** [comment]
Closing outdated issue
